version: 2
updates:
- package-ecosystem: "gradle"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  assignees:
    - "espen42"
  reviewers:
    - "espen42"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 10
  assignees:
    - "espen42"
  reviewers:
    - "espen42"
- package-ecosystem: "npm"
  directory: "/packages/buildcomponents"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 10
  assignees:
    - "espen42"
  reviewers:
    - "espen42"
- package-ecosystem: "npm"
  directory: "/packages/client"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 10
  assignees:
    - "espen42"
  reviewers:
    - "espen42"
- package-ecosystem: "npm"
  directory: "/packages/constants"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 10
  assignees:
    - "espen42"
  reviewers:
    - "espen42"
- package-ecosystem: "npm"
  directory: "/packages/externals"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 10
  assignees:
    - "espen42"
  reviewers:
    - "espen42"
- package-ecosystem: "npm"
  directory: "/packages/nashornpolyfills"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 10
  assignees:
    - "espen42"
  reviewers:
    - "espen42"
- package-ecosystem: "npm"
  directory: "/packages/react4xp"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 10
  assignees:
    - "espen42"
  reviewers:
    - "espen42"
- package-ecosystem: "npm"
  directory: "/packages/regions"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 10
  assignees:
    - "espen42"
  reviewers:
    - "espen42"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 10
  assignees:
    - "espen42"
  reviewers:
    - "espen42"
